"""intui.kit.state: engine-free task/lane state model (layer 2 core)."""

from intui.kit.state.activity import ACTIVITY_STATES, ACTIVITY_STYLES, activity_style
from intui.kit.state.artifacts import (
    ARTIFACT_EVENT_TYPES,
    ArtifactStore,
    DiffArtifact,
    DiffFileRow,
    DiffLine,
    DiffLineKind,
    DiffView,
    EvidenceArtifact,
    EvidenceMetric,
    EvidenceRow,
    EvidenceView,
    FileDiff,
    artifacts_slice,
    diff_view,
    evidence_view,
    parse_unified_diff,
    redact,
)
from intui.kit.state.commands import (
    Command,
    CommandEntry,
    CommandRegistry,
    CommandView,
    command_view,
    filter_commands,
    match_score,
)
from intui.kit.state.conversation import (
    CONVERSATION_EVENT_TYPES,
    ConversationEntry,
    ConversationKind,
    ConversationRow,
    ConversationState,
    ConversationView,
    conversation_slice,
    conversation_view,
    prompt_message_event,
)
from intui.kit.state.metrics import (
    METRICS_EVENT_TYPES,
    MetricsSample,
    MetricsState,
    MetricsView,
    human_bytes,
    metrics_slice,
    metrics_view,
    sparkline,
)
from intui.kit.state.model import (
    CORE_STATUSES,
    STATUS_PRESENTATION,
    UNASSIGNED_KEY,
    LaneView,
    TaskBoardState,
    TaskView,
    WorkItemView,
    status_presentation,
)
from intui.kit.state.modes import (
    MODE_EVENT_TYPES,
    ModeEntry,
    ModeState,
    ModeView,
    mode_slice,
    mode_view,
    switch_mode_intent,
)
from intui.kit.state.reduce import TASKBOARD_EVENT_TYPES, taskboard_slice
from intui.kit.state.run_status import (
    RUN_STATUS_EVENT_TYPES,
    run_status_reducer,
    run_status_slice,
)
from intui.kit.state.selectors import (
    ChipRow,
    ChipView,
    ItemRow,
    LaneRow,
    LanesView,
    TaskRow,
    TreeView,
    chip_view,
    lane_status_view,
    lanes_view,
    taskboard_from,
    tree_view,
)
from intui.kit.state.timeline_feed import (
    STATUS_GLYPH,
    TimelineFeedView,
    TimelineRow,
    run_timeline_view,
)
from intui.kit.state.views import (
    VIEW_EVENT_TYPES,
    ViewEntry,
    ViewRouterView,
    ViewState,
    select_view_intent,
    view_router_view,
    view_slice,
)
from intui.kit.state.workspace import (
    WORKSPACE_EVENT_TYPES,
    FileEntry,
    FileNode,
    FileTreeView,
    WorkspaceState,
    copy_path_intent,
    delete_file_intent,
    file_tree_view,
    open_file_intent,
    scan_workspace,
    workspace_slice,
)

#: The canonical event-stream vocabulary: every event ``type`` the bundled
#: reducers consume. Producers can target this; unknown types are tolerated at
#: runtime (reducers pass them through). Cannot drift — it is the union of each
#: reducer module's declared set.
KNOWN_EVENT_TYPES = frozenset(
    TASKBOARD_EVENT_TYPES
    | ARTIFACT_EVENT_TYPES
    | CONVERSATION_EVENT_TYPES
    | MODE_EVENT_TYPES
    | VIEW_EVENT_TYPES
    | RUN_STATUS_EVENT_TYPES
    | WORKSPACE_EVENT_TYPES
    | METRICS_EVENT_TYPES
)

__all__ = [
    "ACTIVITY_STATES",
    "ACTIVITY_STYLES",
    "ARTIFACT_EVENT_TYPES",
    "CONVERSATION_EVENT_TYPES",
    "CORE_STATUSES",
    "KNOWN_EVENT_TYPES",
    "METRICS_EVENT_TYPES",
    "MODE_EVENT_TYPES",
    "RUN_STATUS_EVENT_TYPES",
    "TASKBOARD_EVENT_TYPES",
    "VIEW_EVENT_TYPES",
    "WORKSPACE_EVENT_TYPES",
    "STATUS_GLYPH",
    "STATUS_PRESENTATION",
    "UNASSIGNED_KEY",
    "ArtifactStore",
    "ChipRow",
    "Command",
    "CommandEntry",
    "CommandRegistry",
    "CommandView",
    "ConversationEntry",
    "ConversationKind",
    "ConversationRow",
    "ConversationState",
    "ConversationView",
    "DiffArtifact",
    "DiffFileRow",
    "DiffLine",
    "DiffLineKind",
    "DiffView",
    "EvidenceArtifact",
    "EvidenceMetric",
    "EvidenceRow",
    "EvidenceView",
    "FileDiff",
    "FileEntry",
    "FileNode",
    "FileTreeView",
    "WorkspaceState",
    "ModeEntry",
    "ModeState",
    "ModeView",
    "ViewEntry",
    "ViewRouterView",
    "ViewState",
    "ChipView",
    "ItemRow",
    "LaneRow",
    "LaneView",
    "LanesView",
    "MetricsSample",
    "MetricsState",
    "MetricsView",
    "TaskBoardState",
    "TaskRow",
    "TaskView",
    "TimelineFeedView",
    "TimelineRow",
    "TreeView",
    "WorkItemView",
    "activity_style",
    "artifacts_slice",
    "chip_view",
    "command_view",
    "conversation_slice",
    "conversation_view",
    "copy_path_intent",
    "delete_file_intent",
    "open_file_intent",
    "prompt_message_event",
    "diff_view",
    "evidence_view",
    "file_tree_view",
    "filter_commands",
    "human_bytes",
    "metrics_slice",
    "metrics_view",
    "sparkline",
    "lane_status_view",
    "lanes_view",
    "match_score",
    "mode_slice",
    "mode_view",
    "parse_unified_diff",
    "redact",
    "run_status_reducer",
    "run_status_slice",
    "run_timeline_view",
    "scan_workspace",
    "select_view_intent",
    "status_presentation",
    "switch_mode_intent",
    "view_router_view",
    "view_slice",
    "workspace_slice",
    "taskboard_from",
    "taskboard_slice",
    "tree_view",
]
